# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsBetting', '0008_auto_20170420_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='country',
        ),
        migrations.AddField(
            model_name='team',
            name='crest',
            field=models.ImageField(default=1, upload_to=b'crests/'),
            preserve_default=False,
        ),
    ]
