# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsBetting', '0012_auto_20170507_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='crest',
            field=models.ImageField(upload_to=b'crests/'),
        ),
    ]
