# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsBetting', '0016_event_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='api_id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
