# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsBetting', '0019_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='user',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
    ]
