# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsBetting', '0024_merge_20170524_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sport',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
