# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsBetting', '0026_auto_20170614_0938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantReview',
            new_name='TeamReview',
        ),
    ]
