# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsBetting', '0013_auto_20170507_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
