# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsBetting', '0022_auto_20170522_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.ImageField(null=True, upload_to=b'competitions/'),
        ),
    ]
