# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsBetting', '0022_event_user'),
        ('sportsBetting', '0023_auto_20170523_1408'),
    ]

    operations = [
    ]
